
package course;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CourseOperationsService", targetNamespace = "http://course/", wsdlLocation = "http://localhost:7896/ws/compserver?wsdl")
public class CourseOperationsService
    extends Service
{

    private final static URL COURSEOPERATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException COURSEOPERATIONSSERVICE_EXCEPTION;
    private final static QName COURSEOPERATIONSSERVICE_QNAME = new QName("http://course/", "CourseOperationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7896/ws/compserver?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURSEOPERATIONSSERVICE_WSDL_LOCATION = url;
        COURSEOPERATIONSSERVICE_EXCEPTION = e;
    }

    public CourseOperationsService() {
        super(__getWsdlLocation(), COURSEOPERATIONSSERVICE_QNAME);
    }

    public CourseOperationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURSEOPERATIONSSERVICE_QNAME, features);
    }

    public CourseOperationsService(URL wsdlLocation) {
        super(wsdlLocation, COURSEOPERATIONSSERVICE_QNAME);
    }

    public CourseOperationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURSEOPERATIONSSERVICE_QNAME, features);
    }

    public CourseOperationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourseOperationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CourseOperations
     */
    @WebEndpoint(name = "CourseOperationsPort")
    public CourseOperations getCourseOperationsPort() {
        return super.getPort(new QName("http://course/", "CourseOperationsPort"), CourseOperations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourseOperations
     */
    @WebEndpoint(name = "CourseOperationsPort")
    public CourseOperations getCourseOperationsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://course/", "CourseOperationsPort"), CourseOperations.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURSEOPERATIONSSERVICE_EXCEPTION!= null) {
            throw COURSEOPERATIONSSERVICE_EXCEPTION;
        }
        return COURSEOPERATIONSSERVICE_WSDL_LOCATION;
    }

}
